
import java.sql.Connection;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.text.SimpleDateFormat;
import java.text.ParseException;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ono
 */
public class musteri extends javax.swing.JFrame {

    private kullaniciServisi kullaniciServisi;
    private String username;

    /**
     * Creates new form musteri
     */
    public musteri(String username) {
        initComponents();

        this.username = username;
        jLabel1.setText("Kullanıcı: " + this.username);

        // form icin
        setupRandevularTable();
        setupIptalButon();

        // paneller
        CardLayout cl = (CardLayout) (musteriIcerikPanel.getLayout());
        cl.addLayoutComponent(musteriAnaSayfaPanel, "musteriAnaSayfaPanel");
        cl.addLayoutComponent(musteriRandevuPanel, "musteriRandevuPanel");
        cl.show(musteriIcerikPanel, "anaSayfaPanel");

        Connection conn = TestConnection.getConnection();
        if (conn != null) {
            kullaniciServisi = new kullaniciServisi(conn);
            loadRandevular();
        } else {
            JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
        }

        // GEÇMİŞ TARİHLERİ TAKVİMDE KİLİTLE
        DateChooser.setMinSelectableDate(new java.util.Date());
    }

    // tabloyu tanımlar
    private void setupRandevularTable() {
        // Tablo sütunlarını tanımla
        String[] columnNames = {"Ad Soyad", "Tarih", "Saat", "Plaka", "Araç Bilgileri"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        randevularTable.setModel(model);

        randevularTable.getTableHeader().setReorderingAllowed(false);
        randevularTable.setRowHeight(25);
    }

    // randevu yukleme musteri icin
    private void loadRandevular() {
        if (kullaniciServisi == null) {
            System.out.println("kullaniciServisi çalışmadı");
            return;
        }

        try {
            // Tabloyu temizler
            DefaultTableModel model = (DefaultTableModel) randevularTable.getModel();
            model.setRowCount(0);

            List<kullaniciServisi.Randevu> randevular = kullaniciServisi.getMusteriRandevulari(username);

            for (kullaniciServisi.Randevu randevu : randevular) {
                Object[] row = {
                    randevu.getAdSoyad(),
                    formatDate(randevu.getTarih()),
                    randevu.getSaat(),
                    randevu.getPlaka(),
                    randevu.getAracBilgileri()
                };
                model.addRow(row);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Randevular yüklenirken bir hata oluştu: " + e.getMessage(),
                    "Hata",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    // Tarihi formatlar
    private String formatDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        return sdf.format(date);
    }

    private void setupIptalButon() {
        randevuIptalButon.setEnabled(false);

        randevularTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Seçim değiştiğinde butonun durumunu güncelle
                randevuIptalButon.setEnabled(randevularTable.getSelectedRow() != -1);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        musteriRandevuButon = new javax.swing.JButton();
        anasayfaButon1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        musteriIcerikPanel = new javax.swing.JPanel();
        musteriRandevuPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        TimeChooser = new javax.swing.JComboBox<>();
        AdSoyadText = new javax.swing.JTextField();
        PlakaText = new javax.swing.JTextField();
        AracText = new javax.swing.JTextField();
        GenislikCB = new javax.swing.JComboBox<>();
        YukseklikCB = new javax.swing.JComboBox<>();
        JantCB = new javax.swing.JComboBox<>();
        RandevuOlusturButon = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        musteriAnaSayfaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        randevularTable = new javax.swing.JTable();
        randevuIptalButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 102, 0));

        musteriRandevuButon.setText("Randevu Al");
        musteriRandevuButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriRandevuButonActionPerformed(evt);
            }
        });

        anasayfaButon1.setText("Anasayfa");
        anasayfaButon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaButon1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Geist Light", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Kullanıcı: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(musteriRandevuButon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anasayfaButon1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(anasayfaButon1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musteriRandevuButon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel3);

        musteriIcerikPanel.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Geist Light", 0, 18)); // NOI18N
        jLabel5.setText("Randevu Panel");

        jLabel6.setText("Tarih Seçin");

        jLabel7.setText("Saat Seçin");

        jLabel8.setText("Ad Soyad");

        jLabel9.setFont(new java.awt.Font("Geist Medium", 0, 15)); // NOI18N
        jLabel9.setText("Araç Bilgileri");

        jLabel10.setText("Plaka");

        jLabel11.setText("Maka/Model");

        jLabel14.setText("Lastik Ebatları");

        jLabel15.setText("Genişlik");

        jLabel16.setText("Yükseklik");

        jLabel25.setText("Jant");

        TimeChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00" }));

        AdSoyadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdSoyadTextActionPerformed(evt);
            }
        });

        PlakaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlakaTextActionPerformed(evt);
            }
        });

        AracText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AracTextActionPerformed(evt);
            }
        });

        GenislikCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "185", "195", "205", "215", "225", "235", "245", "255", "265", "315", "385", " " }));

        YukseklikCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40", "45", "50", "55", "60", "65", "70", "75", "80" }));

        JantCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R13", "R14", "R15", "R15C", "R16", "R16C", "R17", "R17.5", "R18", "R19", "R19.5", "R20", "R22.5", " " }));

        RandevuOlusturButon.setText("Randevuyu Oluştur");
        RandevuOlusturButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandevuOlusturButonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Geist Medium", 0, 15)); // NOI18N
        jLabel12.setText("Randevu Bilgileri");

        javax.swing.GroupLayout musteriRandevuPanelLayout = new javax.swing.GroupLayout(musteriRandevuPanel);
        musteriRandevuPanel.setLayout(musteriRandevuPanelLayout);
        musteriRandevuPanelLayout.setHorizontalGroup(
            musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                        .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(53, 53, 53)
                                    .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                                            .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15)
                                                .addComponent(GenislikCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(42, 42, 42)
                                                    .addComponent(jLabel25))
                                                .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                                                    .addComponent(YukseklikCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(JantCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(AdSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PlakaText, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                                .addComponent(RandevuOlusturButon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(83, 83, 83)
                                .addComponent(TimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(69, 69, 69)
                                .addComponent(AracText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(212, 212, 212))
                    .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                        .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        musteriRandevuPanelLayout.setVerticalGroup(
            musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriRandevuPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(TimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AdSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel9)
                .addGap(34, 34, 34)
                .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(PlakaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(AracText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(musteriRandevuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenislikCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YukseklikCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JantCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(RandevuOlusturButon)
                .addGap(94, 94, 94))
        );

        musteriIcerikPanel.add(musteriRandevuPanel, "card3");

        jLabel2.setFont(new java.awt.Font("Geist Light", 0, 18)); // NOI18N
        jLabel2.setText("AnaSayfa");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Geist Light", 0, 14)); // NOI18N
        jLabel3.setText("Yaklaşan Randevularınız");

        randevularTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ad Soyad", "Tarih", "Saat", "Plaka", "Araç Bilgileri"
            }
        ));
        jScrollPane1.setViewportView(randevularTable);

        randevuIptalButon.setText("Randevuyu İptal Et");
        randevuIptalButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randevuIptalButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout musteriAnaSayfaPanelLayout = new javax.swing.GroupLayout(musteriAnaSayfaPanel);
        musteriAnaSayfaPanel.setLayout(musteriAnaSayfaPanelLayout);
        musteriAnaSayfaPanelLayout.setHorizontalGroup(
            musteriAnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriAnaSayfaPanelLayout.createSequentialGroup()
                .addGroup(musteriAnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(randevuIptalButon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(musteriAnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(musteriAnaSayfaPanelLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(musteriAnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(musteriAnaSayfaPanelLayout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        musteriAnaSayfaPanelLayout.setVerticalGroup(
            musteriAnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriAnaSayfaPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(randevuIptalButon)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        musteriIcerikPanel.add(musteriAnaSayfaPanel, "card2");

        jSplitPane2.setRightComponent(musteriIcerikPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteriRandevuButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriRandevuButonActionPerformed
        // TODO add your handling code here:

        CardLayout cl = (CardLayout) (musteriIcerikPanel.getLayout());
        cl.show(musteriIcerikPanel, "musteriRandevuPanel");
    }//GEN-LAST:event_musteriRandevuButonActionPerformed

    private void anasayfaButon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaButon1ActionPerformed
        // TODO add your handling code here:

        CardLayout cl = (CardLayout) (musteriIcerikPanel.getLayout());
        cl.show(musteriIcerikPanel, "musteriAnaSayfaPanel");
    }//GEN-LAST:event_anasayfaButon1ActionPerformed

    private void PlakaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlakaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlakaTextActionPerformed

    private void AracTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AracTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AracTextActionPerformed

    private void RandevuOlusturButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandevuOlusturButonActionPerformed
        try {
            // fieldlerden falan veri alır
            String adSoyad = AdSoyadText.getText().trim();
            String plaka = PlakaText.getText().trim();
            String arac = AracText.getText().trim();
            String genislik = (String) GenislikCB.getSelectedItem();
            String yukseklik = (String) YukseklikCB.getSelectedItem();
            String jant = (String) JantCB.getSelectedItem();
            java.util.Date selectedDate = DateChooser.getDate();
            String saat = (String) TimeChooser.getSelectedItem();

            // kontroller
            if (adSoyad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ad Soyad alanını doldurun!", "Uyarı", JOptionPane.WARNING_MESSAGE);
                AdSoyadText.requestFocus();
                return;
            }

            if (plaka.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Plaka alanını doldurun!", "Uyarı", JOptionPane.WARNING_MESSAGE);
                PlakaText.requestFocus();
                return;
            }

            if (arac.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Araç modeli alanını doldurun!", "Uyarı", JOptionPane.WARNING_MESSAGE);
                AracText.requestFocus();
                return;
            }

            if (selectedDate == null) {
                JOptionPane.showMessageDialog(this, "Lütfen bir tarih seçin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // GEÇMİŞ TARİH KONTROLÜ
            java.util.Calendar calToday = java.util.Calendar.getInstance();
            calToday.set(java.util.Calendar.HOUR_OF_DAY, 0);
            calToday.set(java.util.Calendar.MINUTE, 0);
            calToday.set(java.util.Calendar.SECOND, 0);
            calToday.set(java.util.Calendar.MILLISECOND, 0);

            java.util.Calendar calSelected = java.util.Calendar.getInstance();
            calSelected.setTime(selectedDate);
            calSelected.set(java.util.Calendar.HOUR_OF_DAY, 0);
            calSelected.set(java.util.Calendar.MINUTE, 0);
            calSelected.set(java.util.Calendar.SECOND, 0);
            calSelected.set(java.util.Calendar.MILLISECOND, 0);

            if (calSelected.getTime().before(calToday.getTime())) {
                JOptionPane.showMessageDialog(this, "Geçmiş bir tarihe randevu alamazsınız!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Tarihi SQL formatına dönüştür
            java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());

            kullaniciServisi.randevuOlustur(username, sqlDate, saat, adSoyad, plaka, arac, genislik, yukseklik, jant);
            JOptionPane.showMessageDialog(this, "Randevu başarıyla oluşturuldu!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

            // Tabloyu güncelle
            loadRandevular();

            // Formu temizle
            AdSoyadText.setText("");
            PlakaText.setText("");
            AracText.setText("");
            GenislikCB.setSelectedIndex(0);
            YukseklikCB.setSelectedIndex(0);
            JantCB.setSelectedIndex(0);
            DateChooser.setDate(new java.util.Date());
            TimeChooser.setSelectedIndex(0);

            // Ana sayfaya dön
            CardLayout cl = (CardLayout) (musteriIcerikPanel.getLayout());
            cl.show(musteriIcerikPanel, "musteriAnaSayfaPanel");

        } catch (SQLException e) {
            // Hatalı durumda, exception mesajını kullanıcıya göster
            JOptionPane.showMessageDialog(this, e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RandevuOlusturButonActionPerformed

    private void randevuIptalButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randevuIptalButonActionPerformed
        // TODO add your handling code here:
        int selectedRow = randevularTable.getSelectedRow();
        if (selectedRow != -1) {
            int response = JOptionPane.showConfirmDialog(
                    this,
                    "Seçili randevuyu iptal etmek istediğinize emin misiniz?",
                    "Randevu İptal Onayı",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (response == JOptionPane.YES_OPTION) {
                try {
                    DefaultTableModel model = (DefaultTableModel) randevularTable.getModel();

                    // Seçili satırdan verileri al
                    String tarihStr = model.getValueAt(selectedRow, 1).toString();
                    String saat = model.getValueAt(selectedRow, 2).toString();

                    // Tarihi parse et
                    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                    java.util.Date utilDate = sdf.parse(tarihStr);
                    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

                    // Randevuyu iptal et
                    kullaniciServisi.randevuIptal(username, sqlDate, saat);

                    // Tabloyu güncelle
                    loadRandevular();

                    JOptionPane.showMessageDialog(
                            this,
                            "Randevu başarıyla iptal edildi.",
                            "Başarılı",
                            JOptionPane.INFORMATION_MESSAGE
                    );

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(
                            this,
                            "Randevu iptal edilirken bir hata oluştu: " + e.getMessage(),
                            "Hata",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        }

    }//GEN-LAST:event_randevuIptalButonActionPerformed

    private void AdSoyadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdSoyadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdSoyadTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdSoyadText;
    private javax.swing.JTextField AracText;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JComboBox<String> GenislikCB;
    private javax.swing.JComboBox<String> JantCB;
    private javax.swing.JTextField PlakaText;
    private javax.swing.JButton RandevuOlusturButon;
    private javax.swing.JComboBox<String> TimeChooser;
    private javax.swing.JComboBox<String> YukseklikCB;
    private javax.swing.JButton anasayfaButon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel musteriAnaSayfaPanel;
    private javax.swing.JPanel musteriIcerikPanel;
    private javax.swing.JButton musteriRandevuButon;
    private javax.swing.JPanel musteriRandevuPanel;
    private javax.swing.JButton randevuIptalButon;
    private javax.swing.JTable randevularTable;
    // End of variables declaration//GEN-END:variables
}
